name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
        - {
            os: windows-2019,
            name: windows
          }
        - {
            os: macos-13,
            name: macos
          }
        - {
            os: ubuntu-22.04,
            name: ubuntu
          }
        version:
        - name: v5.0.7290-stable
          use-patch: false
        - name: dev
          use-patch: false
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Update submodule
      run: |
        cd binaryninjaapi
        git fetch --tags
        git checkout --force ${{matrix.version.name}}
        git submodule update --init --recursive
    - name: Patch api to allow building headlessly
      if: ${{ matrix.version.use-patch }}
      shell: bash
      run: |
        cd binaryninjaapi
        git apply --verbose ${{matrix.version.patch-file}} 
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{matrix.config.name}}-${{matrix.version.name}}
        path: ${{github.workspace}}/build/libarch_arcompact.so
